# .github/workflows/deploy.yml
name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Set lowercase repo owner
      run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
  
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ env.REPO_OWNER_LC }}/oeeg_image:latest .
        
    - name: Push Docker image to GHCR
      run: |
        docker push  ghcr.io/${{ env.REPO_OWNER_LC }}/oeeg_image:latest

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.OEEG_SERVER }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 91.98.20.253 >> ~/.ssh/known_hosts
    
    - name: Deploy on server
      run: |
        ssh -i ~/.ssh/id_ed25519 root@91.98.20.253 "
          echo '${{ secrets.GHCR_TOKEN }}' | docker login ghcr.io -u ${{ github.repository_owner }} --password
          docker stop oeeg_container || true
          docker rm oeeg_container || true
          docker pull ghcr.io/${{ env.REPO_OWNER_LC }}/oeeg_image:latest
          docker run -d --name oeeg_container -p 80:8501 -v ~/data:/app/data ghcr.io/${{ env.REPO_OWNER_LC }}/oeeg_image:latest
        "
